package(default_visibility = ["//actions:__subpackages__"])

cc_library(
    name = "stub_connection",
    srcs = ["stub_connection.cc"],
    hdrs = ["stub_connection.h"],
    deps = [
        "//actions/internal:connection",
        "//actions/internal:util",
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
    ],
)
