package(default_visibility = ["//actions/internal:__pkg__"])

cc_library(
    name = "xcb_error",
    srcs = ["xcb_error.cc"],
    hdrs = ["xcb_error.h"],
    deps = [
        "@com_google_absl//absl/status",
        "@xcb",
    ],
)
