package(default_visibility = ["//visibility:public"])

cc_library(
    name = "action",
    hdrs = ["action.h"],
    deps = [
        "//actions/action:keystroke",
        "@com_google_absl//absl/types:variant",
    ],
)
