[package]
name = "jesture_display_actions"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = "2"
napi-derive = "2"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"
x11 = "2.20.0"

[build-dependencies]
napi-build = "2"