package(default_visibility = "//actions:__subpackages__")

cc_library(
    name = "connection",
    hdrs = ["connection.h"],
    deps = [
        "//actions:action",
        "@com_google_absl//absl/status",
    ],
)
